In [8]:
import yfinance as yf
import pandas as pd
from datetime import datetime

In [11]:
tickers = [
    'PETR4.SA',  # Petrobras
    'VALE3.SA',  # Vale
    'ITUB4.SA',  # Itaú Unibanco
    'BBDC4.SA',  # Bradesco
    'BBAS3.SA',  # Banco do Brasil
    'ABEV3.SA',  # Ambev
    'B3SA3.SA',  # B3
    'WEGE3.SA',  # WEG
    'RENT3.SA',  # Localiza
    'JBSS3.SA',  # JBS
    'MGLU3.SA',  # Magazine Luiza
    'BRFS3.SA',  # BRF
    'SUZB3.SA',  # Suzano
    'GGBR4.SA',  # Gerdau
    'CSNA3.SA',  # CSN
    'LREN3.SA',  # Lojas Renner
    'RAIL3.SA',  # Rumo
    'KLBN11.SA', # Klabin
    'EGIE3.SA',  # Engie Brasil
    'ELET3.SA'   # Eletrobras
]


start_date = '2024-01-01'
end_date = datetime.today().strftime('%Y-%m-%d')
select_ticker = input('Enter ticker symbol (Exemplo: PETR4.SA): ')

df = yf.download(select_ticker, start_date, end_date)
df1 = pd.DataFrame(df)
df1

[*********************100%***********************]  1 of 1 completed

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,PETR4.SA,PETR4.SA,PETR4.SA,PETR4.SA,PETR4.SA,PETR4.SA
Date,,,,,,
2024-01-02 00:00:00+00:00,33.281128,37.779999,37.889999,37.400002,37.439999,24043800
2024-01-03 00:00:00+00:00,34.320610,38.959999,39.119999,37.669998,37.799999,52300200
2024-01-04 00:00:00+00:00,34.029907,38.630001,39.349998,38.509998,39.119999,45344900
2024-01-05 00:00:00+00:00,34.109192,38.720001,39.139999,38.410000,38.869999,35783700
2024-01-08 00:00:00+00:00,33.853729,38.430000,38.430000,37.610001,38.380001,35158100
...,...,...,...,...,...,...
2024-11-06 00:00:00+00:00,35.400002,35.400002,35.459999,35.040001,35.049999,28440800
2024-11-07 00:00:00+00:00,35.509998,35.509998,35.889999,35.270000,35.490002,34081200
2024-11-08 00:00:00+00:00,36.180000,36.180000,36.320000,35.540001,35.849998,49865100
2024-11-11 00:00:00+00:00,36.250000,36.250000,36.419998,35.900002,35.990002,21446300
2024-11-12 00:00:00+00:00,36.930000,36.930000,37.110001,36.340000,36.360001,39412300